### ISSUE TITLE
Can't find  pretrained and finetuned models  on project page

### ISSUE THREAD

**Issue by ousinkou** [Morpheus3000/PIE-Net#1]
Thanks for this great work. But I can't find  pretrained or finetuned models for testing. Hoping for help.

**Comment by Morpheus3000** [comment]
Hello,

Thank you for your interest in the work. There is some internal issue with the hosting of the files. I am working getting it back up and will get back to you shortly. Apologies for the inconvenience.

**Comment by mhr380** [comment]
Hello.
Thank you for your nice work.

I also have interested in trained models for testing. 
I hope for your help.

**Comment by Morpheus3000** [comment]
Hello all,

The pretrained model is now live at https://uvaauas.figshare.com/articles/conference_contribution/real_world_model_t7/19940000

The main repository readme has also been updated to reflect the same. Thanks for your patience.

**Comment by mhr380** [comment]
Thanks a lot!
