### ISSUE TITLE
How to process the NED dataset and get reflectance and shading images

### ISSUE THREAD

**Issue by guozonghui** [Morpheus3000/PIE-Net#2]
Many thanks for your open source project! I downloaded the NED dataset from the website (https://ivi.fnwi.uva.nl/cv/intrinseg), and found that there seems to be only a lot of mat files, how can I process this data to get reflectance and shading images? Thinks for your help.

**Comment by Morpheus3000** [comment]
Hi,

You need to read in the mat files using either Matlab, or use a python library like scipy, which support reading mat files. Then you can extract the image files from there.
