### ISSUE TITLE
Can we change the resolution?

### ISSUE THREAD

**Issue by Yuchen-Song** [Morpheus3000/PIE-Net#4]
Hi, brilliant work!
I wonder can I make the output image resolution higher? Or should it be fixed to 256*256 due to the network setting or something?

**Comment by Morpheus3000** [comment]
Hello, thanks for your interest in the work!

Technically, it should be possible to use higher resolution, since I use only convolutions. But I haven't tested it. I would be very interested if it runs.

**Comment by Morpheus3000** [comment]
Closing the issue, since no reply from the OP.
